"""empty message

Revision ID: 101a10ebb497
Revises: f5ec361d9c26
Create Date: 2017-11-26 23:30:17.412301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101a10ebb497'
down_revision = 'f5ec361d9c26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('viewsnum', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'viewsnum')
    # ### end Alembic commands ###
