"""empty message

Revision ID: 5ef5538ab795
Revises: 101a10ebb497
Create Date: 2017-11-27 00:34:35.109297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ef5538ab795'
down_revision = '101a10ebb497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('viewsnum', sa.Integer(), server_default=sa.text('0'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'viewsnum')
    # ### end Alembic commands ###
